// FHIR R4 schema validation tests (FHIR-EX-03).
//
// Uses AJV + the vendored FHIR R4 schema at test-fixtures/fhir/fhir.schema.json
// to assert that the Bundle generated by generateFhirBundle is spec-valid.
//
// Also enforces the production-bundle invariant: validate.ts must NOT be
// imported by any production source path (13-02 D-06).
//
// First test run takes ~1-3s (AJV schema compilation). Subsequent runs reuse
// the cached validator and are faster.

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { generateFhirBundle } from '@/lib/exportFhir';
import type { FhirBundle, FhirPatient, FhirObservation } from '@/lib/exportFhir';
import { validateFhirBundle } from '@/lib/exportFhir/validate';
import type { DiaryState } from '@/lib/types';

function buildMinimalDiaryState(overrides: Partial<DiaryState> = {}): DiaryState {
  const base: DiaryState = {
    startDate: '2026-05-18',
    age: 55,
    volumeUnit: 'mL',
    hapticEnabled: true,
    diaryStarted: true,
    clinicCode: null,
    timeZone: 'America/New_York',
    morningAnchor: null,
    day1CelebrationShown: false,
    fmvTooltipShown: false,
    voids: [
      {
        id: 'v1',
        timestampIso: '2026-05-18T08:30:00.000Z',
        volumeMl: 250,
        sensation: null,
        leak: false,
        note: '',
        isFirstMorningVoid: true,
      },
      {
        id: 'v2',
        timestampIso: '2026-05-19T07:15:00.000Z',
        volumeMl: 300,
        doubleVoidMl: 80,
        sensation: null,
        leak: false,
        note: '',
        isFirstMorningVoid: true,
      },
      {
        id: 'v3',
        timestampIso: '2026-05-20T08:00:00.000Z',
        volumeMl: 280,
        sensation: null,
        leak: false,
        note: '',
        isFirstMorningVoid: true,
      },
    ],
    drinks: [
      {
        id: 'd1',
        timestampIso: '2026-05-18T09:00:00.000Z',
        volumeMl: 240,
        drinkType: 'coffee',
        note: '',
      },
    ],
    leaks: [
      {
        id: 'l1',
        timestampIso: '2026-05-19T15:00:00.000Z',
        trigger: 'cough',
        urgencyBeforeLeak: null,
      },
    ],
    bedtimes: [
      { id: 'b1', timestampIso: '2026-05-18T22:30:00.000Z', dayNumber: 1 },
      { id: 'b2', timestampIso: '2026-05-19T22:00:00.000Z', dayNumber: 2 },
      { id: 'b3', timestampIso: '2026-05-20T22:15:00.000Z', dayNumber: 3 },
    ],
    wakeTimes: [
      { id: 'w1', timestampIso: '2026-05-19T07:00:00.000Z', dayNumber: 1 },
      { id: 'w2', timestampIso: '2026-05-20T07:00:00.000Z', dayNumber: 2 },
      { id: 'w3', timestampIso: '2026-05-21T07:00:00.000Z', dayNumber: 3 },
    ],
  };
  return { ...base, ...overrides };
}

/** Deep clone via JSON. Returns the value typed as unknown so test code can mutate freely. */
function deepClone<T>(value: T): unknown {
  return JSON.parse(JSON.stringify(value));
}

describe('FHIR R4 schema validation (AJV)', () => {
  // Warm the AJV validator once. First compile of the FHIR R4 schema takes
  // ~2-5 seconds (RESEARCH §AJV CI cost). The cache inside validate.ts means
  // every subsequent call is microseconds. Bumping the hook timeout to 30s
  // so slow CI runners do not flake on a one-time setup cost.
  beforeAll(() => {
    const warm = generateFhirBundle(buildMinimalDiaryState());
    validateFhirBundle(warm);
  }, 30_000);

  it('valid Bundle passes the R4 schema', () => {
    const bundle = generateFhirBundle(buildMinimalDiaryState());
    const result = validateFhirBundle(bundle);
    if (!result.valid) {
      // Surface errors before the assertion so debugging is easier.
      console.error('FHIR validation errors:', JSON.stringify(result.errors, null, 2));
    }
    expect(result.valid, 'synthetic Bundle passes R4 schema per 13-02 FHIR-EX-03').toBe(true);
    expect(result.errors, 'no errors when valid per 13-02').toEqual([]);
  });

  it('errors array is empty when valid is true', () => {
    const bundle = generateFhirBundle(buildMinimalDiaryState());
    const result = validateFhirBundle(bundle);
    if (result.valid) {
      expect(result.errors.length, 'errors empty when valid').toBe(0);
    }
  });

  it('Bundle missing resourceType is rejected', () => {
    const bundle = generateFhirBundle(buildMinimalDiaryState());
    const malformed = deepClone(bundle) as Record<string, unknown>;
    delete malformed.resourceType;
    const result = validateFhirBundle(malformed);
    expect(result.valid, 'missing resourceType rejected per 13-02 FHIR-EX-03').toBe(false);
    expect(result.errors.length, 'errors collected per D-07 allErrors:true').toBeGreaterThan(0);
  });

  it('Observation missing required code field is rejected', () => {
    // The FHIR R4 JSON Schema marks "code" and "resourceType" as required on
    // Observation. "subject" is cardinality 1..1 in the spec narrative but
    // not in required[] in this schema. We delete code (which IS required[])
    // so the negative case fires deterministically against this fixture.
    const bundle = generateFhirBundle(buildMinimalDiaryState());
    const malformed = deepClone(bundle) as FhirBundle;
    // Entry index 2 is the first Observation (after Patient at 0, QR at 1).
    const firstObs = malformed.entry[2].resource as Partial<FhirObservation>;
    delete firstObs.code;
    const result = validateFhirBundle(malformed);
    expect(result.valid, 'Observation missing code rejected per 13-02 FHIR-EX-03').toBe(false);
    expect(result.errors.length).toBeGreaterThan(0);
  });

  it('Patient with day-precision birthDate: layered defense (AJV schema or PHI audit)', () => {
    // FHIR R4 schema permits BOTH year and day precision for birthDate. The PHI audit
    // pattern in fhir-bundle-shape.test.ts is the layer that enforces year-only.
    // This test documents the layered defense: even if the schema accepts day precision,
    // the shape test catches it. We don't assert AJV failure here. Just that
    // generateFhirBundle never produces day-precision birthDate.
    const bundle = generateFhirBundle(buildMinimalDiaryState());
    const patient = bundle.entry[0].resource as FhirPatient;
    expect(patient.birthDate, 'birthDate year-only by construction per 13-01').toMatch(/^\d{4}$/);
    expect(patient.birthDate, 'no day precision').not.toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it('empty diary still produces a schema-valid Bundle (Patient + QR only)', () => {
    const bundle = generateFhirBundle(
      buildMinimalDiaryState({ voids: [], drinks: [], leaks: [] }),
    );
    expect(bundle.entry.length, 'Patient + QR per 13-02').toBe(2);
    const result = validateFhirBundle(bundle);
    if (!result.valid) {
      console.error('Empty-diary FHIR errors:', JSON.stringify(result.errors, null, 2));
    }
    expect(result.valid, 'empty Bundle passes schema per 13-02 FHIR-EX-03').toBe(true);
  });
});

describe('Production-bundle invariant: validate.ts must not be imported by client code', () => {
  it('no production source file imports from @/lib/exportFhir/validate', () => {
    const PRODUCTION_ROOTS = [
      'src/app',
      'src/components',
      'src/lib/exportPackage',
      'src/lib/exportPdf',
    ];

    function walk(dir: string, offenders: string[]): void {
      if (!existsSync(dir)) return;
      const entries = readdirSync(dir);
      for (const e of entries) {
        const p = join(dir, e);
        const s = statSync(p);
        if (s.isDirectory()) {
          walk(p, offenders);
        } else if (p.endsWith('.ts') || p.endsWith('.tsx')) {
          const content = readFileSync(p, 'utf8');
          if (content.includes('@/lib/exportFhir/validate')) {
            offenders.push(p);
          }
        }
      }
    }

    const offenders: string[] = [];
    for (const root of PRODUCTION_ROOTS) {
      walk(root, offenders);
    }
    expect(
      offenders,
      'No production source must import validate.ts per 13-02 D-06',
    ).toEqual([]);
  });

  it('exportFhir/index.ts barrel does not re-export validate.ts', () => {
    const barrel = readFileSync('src/lib/exportFhir/index.ts', 'utf8');
    expect(
      barrel.includes('./validate'),
      'barrel must not export validate.ts per 13-02 D-06',
    ).toBe(false);
    expect(
      barrel.includes('validateFhirBundle'),
      'barrel must not re-export validateFhirBundle per 13-02 D-06',
    ).toBe(false);
  });
});
